language: node_js
node_js:
- 10.8.0
cache:
  directories:
  - node_modules
services: mongodb
script:
- npm run test
before_install:
- openssl aes-256-cbc -K $encrypted_8794bff736b3_key -iv $encrypted_8794bff736b3_iv
  -in .env.enc -out .env -d
